name: Codecov
run-name: ${{ github.actor }} uploaded coverage reports to Codecov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: upload coverage reports to Codecov
    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
