name: test coverage
run-name: ${{ github.actor }} ${{ github.event_name }}; Setup testenv, run tests, upload coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Setup testenv, run tests, upload coverage  
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install requirements #' Using requirements.txt should be faster
      run: pip install -r requirements.txt
    - name: Install plotastic (in editable mode! Otherwise 0% coverage)
      run: pip install -e .[dev]
    - name: Run tests and collect coverage
      run: pytest tests --cov --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}