name: test
run-name: ${{ github.actor }} tested  when ${{ github.event_name }}

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test ${{ matrix.repo }} # This will be the name of the job
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: pytest --cov .
    - name: Upload coverage reports to Codecov
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://uploader.codecov.io/latest/macos/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}